services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: veterinaria
      MYSQL_USER: veterinaria_user
      MYSQL_PASSWORD: veterinaria_pass
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build: ./veterinaria-backend
    container_name: veterinaria_backend
    volumes:
      - ./veterinaria-backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: db 
      DATABASE_NAME: veterinaria
      DATABASE_USER: veterinaria_user
      DATABASE_PASS: veterinaria_pass
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "sleep 10 && 
      python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
